# permissions for end users to view sandboxes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sandbox-viewer-role
rules:
- apiGroups:
  - cache.my.domain
  resources:
  - sandboxes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.my.domain
  resources:
  - sandboxes/status
  verbs:
  - get
